name: Community Feedback Auto Comment
description: Adds a comment to issues labeled with "needs community feedback"

inputs:
  issue-number:
    description: 'The issue number to add the comment to'
    required: true
  comment-author:
    description: 'The username of the comment author to look for'
    default: 'github-actions[bot]'

runs:
  steps:
    - name: Get Comments
      id: comments
      uses: actions/github-script@v4
      with:
        script: |
          const { data: comments } = await github.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: ${{ inputs.issue-number }},
          });
          const filtered = comments.filter(comment => comment.user.login === '${{ inputs.comment-author }}' && comment.body.includes('Thanks for the feature request! We are going to give the community'));
          return { commentId: filtered[0]?.id };

    - name: Add Community Feedback Comment
      if: ${{ !steps.comments.outputs.commentId }}
      uses: actions/github-script@v4
      with:
        script: |
          await github.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: ${{ inputs.issue-number }},
            body: 'Thanks for the feature request! We are going to give the community 60 days from when this issue was created to provide 7 👍 upvotes on the opening comment to gauge general interest in this idea. If there\'s enough upvotes then we will consider this feature request in our future planning. If there\'s unfortunately not enough upvotes then we will close this issue.'
          });
