name: Lock Issues

inputs:
  token:
    description: 'GitHub token'
    default: ${{ github.token }}
    required: true
  issue-inactive-days:
    description: 'Issue inactive days'
    default: '30'
    required: false

runs:
  using: 'composite'
  steps:
    - uses: dessant/lock-threads@v4
      with:
        github-token: ${{ inputs.token }}
        issue-inactive-days: ${{ inputs.issue-inactive-days }}
        process-only: 'issues'
        log-output: true